### PR TITLE
Add FQN of class , remove --dev dependency

### PR DESCRIPTION
**Pull request by harikt**
Hi @everzet , 

I have removed the `--dev` prefix from installation for 

I believe the other repositories will have a dependency on the https://github.com/everzet/persisted-objects/blob/master/src/Repository.php interface .

Thanks

### CODE REVIEW

**Comment by everzet** [comment]
I don't think your production code should depend on anything in `PersistedObjects`.

**Comment by harikt** [comment]
@everzet so may be you mean we should have a different repository interface for our own ?

I was also having an idea of keeping a criteria class in this repo. So the repository can accept the Criteria which have the ability to sort etc. But now I think your views seems not into that way .

Thank you.

**Comment by ciaranmcnulty** [comment]
Yes you would normally use this inside your own repository; a repository interface is a core part of your own domain so you should own it.

**Comment by harikt** [comment]
Closing the PR .

**Pull request closed without merging**
